import type { ArticlePublicDetail } from '@siders/contracts';
import { Button } from './ui/Button.js';

/**
 * Renders the same sanitized `bodyHtml` the public site would render, without changing the
 * article's status (specs/article-management/spec.md - "Article preview"). Safe to inject
 * directly — `bodyHtml` is server-generated by the allowlist renderer in
 * `apps/api/src/lib/sanitizeHtml.ts`, never raw user input.
 */
export function PreviewModal({ article, onClose }: { article: ArticlePublicDetail; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 p-4 pt-12">
      <div className="siders-scope w-full max-w-3xl rounded-lg bg-[var(--paper)] text-[var(--ink)] shadow-xl">
        <div className="flex items-center justify-between border-b border-[var(--rule)] p-4">
          <span className="font-mono text-xs uppercase tracking-wide text-[var(--muted)]">Preview</span>
          <Button type="button" variant="ghost" onClick={onClose}>
            Close
          </Button>
        </div>
        <article className="prose dark:prose-invert max-w-none p-8">
          <h1 className="font-['Fraunces']">{article.title}</h1>
          {article.featuredImageUrl && (
            <img src={article.featuredImageUrl} alt={article.title} className="w-full rounded-lg" />
          )}
          <div dangerouslySetInnerHTML={{ __html: article.bodyHtml }} />
        </article>
      </div>
    </div>
  );
}
